services:

    app.security.interactive_login_listener:
        class: AppBundle\EventListener\AuthenticationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.authorization_checker'
            - '@security.token_storage'
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }


    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HasherPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }