#web debug toolbar at the bottom of each page
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

#Symfony Profiler info
_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

# /{_locale}/_error/{status_code}.{format}
# (e.g. /en/_error/404, /en/_error/403.json, /fr/_error/500.xml)
_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /{_locale}/_error
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

###simply error pages debug
errorpage_check:
    path: /{_locale}/e/{code}
    defaults:
            _controller: AppBundle:Security:error
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'


# this loads the main routing file, which usually defines the routes available
# in any environment (production, development, etc.)
_main:
    resource: routing.yml
